### ISSUE TITLE
TypeError: Cannot read property 'entries' of null

### ISSUE THREAD

**Issue by christianbundy** [staltz/ssb-conn-db#1]
I'm writing some tests for Oasis, but they seem to be failing when I run `server.close()` to exit the Secret-Stack server. I might be doing something wrong, any ideas what might be breaking here?

```
Oasis: Closing server
fallback to close
TypeError: Cannot read property 'entries' of null
    at ConnDB._serialize (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn-db/lib/index.js:141:46)
    at ConnDB._write (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn-db/lib/index.js:157:27)
    at Timeout._onTimeout (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn-db/lib/index.js:174:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by christianbundy** [comment]
I've modified the JS to check for the server being closed before throwing:

```js
    ConnDB.prototype._serialize = function () {
        var e_2, _a;
        var record = {};
        try {
            for (var _b = __values(this._map.entries()), _c = _b.next(); !_c.done; _c = _b.next()) {
                var _d = __read(_c.value, 2), address = _d[0], data = _d[1];
                record[address] = data;
            }
        }
        catch (e_2_1) { e_2 = { error: e_2_1 }; }
        finally {
            try {
                if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
            }
            finally { if (e_2 && this._closed === false) throw e_2.error; }
        }
        return record;
    };
```

But now I'm getting:

```
test/basic.js 2>     at ConnDB._write (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn-db/lib/index.js:158:25)
test/basic.js 2>     at Timeout._onTimeout (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn-db/lib/index.js:174:19)
test/basic.js 2>     at listOnTimeout (internal/timers.js:549:17)
test/basic.js 2>     at processTimers (internal/timers.js:492:7)
```

**Comment by christianbundy** [comment]
It looks like `this._map.clear()` is setting `this._map` to `null` and doing the same for `this._stateFile`. My guess is that we need to sprinkle in some `assertNotClosed()` in there, but that the real bug is me maintaining a naive script to emulate `conn.hops` here: https://github.com/staltz/ssb-conn/issues/16

**Comment by staltz** [comment]
@christianbundy I don't understand this bug. `this._map` is only `null` when `connDB.close()` is called. But `connDB.close()` will also cancel any existing `setTimeout`...

I released ssb-conn-db 0.3.2 with some more assertions, try that out. But I'm not sure it'll solve it.

**Comment by christianbundy** [comment]
```
test/lifecycle.js 1>   message: 'This ConnStaging instance is closed, create a new one.',
test/lifecycle.js 1>   name: 'Error',
test/lifecycle.js 1>   stack: 'Error: This ConnStaging instance is closed, create a new one.\n' +
test/lifecycle.js 1>     '    at ConnStaging._assertNotClosed (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn-staging/lib/index.js:27:19)\n' +
test/lifecycle.js 1>     '    at ConnStaging.liveEntries (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn-staging/lib/index.js:77:14)\n' +
test/lifecycle.js 1>     '    at Object.CONN.stagedPeers (/home/christianbundy/src/fraction/oasis/node_modules/ssb-conn/lib/conn.js:61:48)\n' +
test/lifecycle.js 1>     '    at Object.hooked (/home/christianbundy/src/fraction/oasis/node_modules/hoox/index.js:10:15)\n' +
test/lifecycle.js 1>     '    at Object.localCall (/home/christianbundy/src/fraction/oasis/node_modules/muxrpc/local-api.js:31:29)\n' +
test/lifecycle.js 1>     '    at Object.<anonymous> (/home/christianbundy/src/fraction/oasis/node_modules/muxrpc/local-api.js:37:22)\n' +
test/lifecycle.js 1>     '    at PacketStreamSubstream.stream.read (/home/christianbundy/src/fraction/oasis/node_modules/muxrpc/stream.js:69:23)\n' +
test/lifecycle.js 1>     '    at PacketStream._onstream (/home/christianbundy/src/fraction/oasis/node_modules/packet-stream/index.js:228:11)\n' +
test/lifecycle.js 1>     '    at PacketStream.write (/home/christianbundy/src/fraction/oasis/node_modules/packet-stream/index.js:135:41)\n' +
test/lifecycle.js 1>     '    at /home/christianbundy/src/fraction/oasis/node_modules/muxrpc/pull-weird.js:56:15'
test/lifecycle.js 1> }
```

Woo!

**Comment by staltz** [comment]
Wait, does this mean it's resolved for you? Or do we have a new issue for conn-staging (not conn-db)?

**Comment by christianbundy** [comment]
Yep, this is resolved for me. The bug was coming from my hacky scheduler add-on, which was running `ssb.connect()` on staged peers (and didn't have any `close()` handling). My approach is super fraught, I've opened a PR to make the replication hops configurable (https://github.com/staltz/ssb-conn/pull/17) but can just fork SSB-CONN if it isn't something you'd like to merge.
