### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by SharkyRawr** [staltz/ssb-conn-db#4]
```
TypeError: Cannot read property 'toString' of undefined
    at Object.decode (/Users/luna/checkouts/patchwork/node_modules/ssb-conn-db/lib/atomic-file-codecs.js:9:27)
    at /Users/luna/checkouts/patchwork/node_modules/ssb-conn-db/lib/index.js:89:80
    at /Users/luna/checkouts/patchwork/node_modules/atomic-file-rw/browser.js:22:12
    at intercept (/Users/luna/checkouts/patchwork/node_modules/promisize/index.js:22:15)
    at IDBRequest.request.onsuccess (/Users/luna/checkouts/patchwork/node_modules/idb-kv-store/index.js:333:7)
```
added a simple fix for now: 
```
9   decode: function (input) {
10      if (!input) return {};
11      const str = input.toString();
```

**Comment by staltz** [comment]
Oh yes, that's the right solution.
